In [64]:
from pathlib import Path
import json
import pandas as pd


BASE_DIR = Path("main.ipynb").resolve().parents[1]
DATA_DIR = BASE_DIR / "data" / "processed"

JSON_PATH = DATA_DIR / "survey_v1.1.json" # survey1 not survey

df = pd.read_json(JSON_PATH)

In [65]:
df.head()

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,REN_6,REN_7,REN_Year,REF_1,REF_2,REF_3,REF_4,REF_5,REF_6,REF_7,REF_8,REF_9,REF_10,REF_11,REF_Year,NEW_Type,NEW_ES_Con0,NEW_ES_Con1,NEW_ES_Con2,NEW_ES_Con3,NEW_ES_Con4,NEW_ES_Con5,NEW_HS_Con0,NEW_HS_Con1,NEW_HS_Con2,NEW_HS_Con3,NEW_HS_Con4,NEW_HS_Con5,NEW_HS_Con6,NEW_HS_Con7,NEW_HS_Con8,NEW_HS_Con9,NEW_HP_Con0,NEW_HP_Con1,NEW_HP_Con2,NEW_HP_Con3,NEW_HP_Con4,NEW_HP_Con5,NEW_Year,TRIG_1Text,TRIG_2Text,TRIG_1,TRIG_2,TRIG_3,TRIG_4,SUB,SUB_1,SUB_2,SUB_3,SUB_5,SUB_4,INFO_S1,INFO_S2,INFO_S3,INFO_S4,INFO_S5,INFO_S6,INFO_S7,INFO_S8,INFO_S9,INFO_S10,INFO_S11,INFO_S12,INFO_C1,INFO_C2,INFO_C3,INFO_C4,INFO_C5,INFO_C6,INFO_C7,INFO_C8,INFO_C9,INFO_PAS,INFO_ACT,CHAR_B1,CHAR_B2,CHAR_B3,CHAR_B4,CHAR_HS1,CHAR_HS2,CHAR_HS3,CHAR_HS4,CHAR_HS5,CHAR_HS6,CHAR_HS7,BUILD_Type,BUILD_Size,BUILD_Use,BUILD_Use_Year,BUILD_Residence,BUILD_Age,BUILD_ES_Cur,BUILD_ES_Old,BUILD_HS1,BUILD_HS2,BUILD_HS3,BUILD_HS4,BUILD_HS5,BUILD_HS6,BUILD_HS7,BUILD_HS8,BUILD_HS9,BUILD_HS10,BUILD_HP,BUILD_HS1_Old,BUILD_HS2_Old,BUILD_HS3_Old,BUILD_HS4_Old,BUILD_HS5_Old,BUILD_HS6_Old,BUILD_HS7_Old,BUILD_HS8_Old,BUILD_HS9_Old,BUILD_HS10_Old,BUILD_HS_Age,SOCIO_Gender1,SOCIO_Age1,SOCIO_Country1,HOUSE_Education,HOUSE_Size1,HOUSE_Size2,HOUSE_Size3,HOUSE_Size4,HOUSE_Size5,HOUSE_Size6,HOUSE_Size7,HOUSE_Size8,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer,Gemeindename
0,1,1,1,0,0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,2022,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,NaN,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Hoher Energieverbrauch, Kälte von unten",Auszug der Mutter ins Altersheim,3.0,1.0,1.0,4.0,1.0,NaN,1.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,3.0,3.0,3,2.0,3,1,2.0,4.0,3.0,1.0,3.0,5.0,2.0,1,2.0,1,46.0,1.0,5,6.0,6.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2014,1.0,1966.0,5.0,4.0,0.0,0,0,0,0,1,1,0,4.0,1,1,1.0,61263,Rottenmann
1,2,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2018,Familiengründung - Geburt von Kindern,Umzug von Wien in die Oststeiermark,2.0,2.0,NaN,2.0,1.0,NaN,1.0,NaN,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,3.0,NaN,3,2.0,3,1,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1,1.0,1,5.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,2.0,1984.0,1.0,4.0,2.0,0,0,0,2,0,0,0,5.0,0,0,5.0,62233,Pinggau
2,3,0,1,0,0,1.0,1.0,0.0,0.0,0.0,1.0,NaN,vor 2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,2.0,3.0,2.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,3.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,3.0,3.0,3,1.0,3,1,1.0,4.0,4.0,1.0,1.0,1.0,2.0,1,2.0,1,9.0,1.0,5,4.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,2.0,1977.0,1.0,3.0,0.0,1,0,0,0,1,0,0,3.0,0,0,NaN,61255,Bad Mitterndorf
3,4,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Haus war renovierungsbedürftig,Alte Fassade aus Eternit,1.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,3.0,3,2.0,2,2,3.0,2.0,3.0,1.0,1.0,3.0,5.0,1,1.0,0,NaN,1.0,4,3.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,2.0,1959.0,1.0,3.0,0.0,0,0,0,0,0,2,0,3.0,1,1,1.0,60350,Stainz
4,5,1,1,0,0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,vor 2010,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,NaN,vor 2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Hauskauf,None,1.0,1.0,1.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,3.0,4,1.0,4,1,1.0,4.0,4.0,1.0,1.0,1.0,1.0,1,1.0,1,4.0,1.0,6,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,2.0,1971.0,1.0,4.0,0.0,0,2,0,0,2,0,0,4.0,1,1,1.0,61757,Birkfeld

In [66]:
df.tail()

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,REN_6,REN_7,REN_Year,REF_1,REF_2,REF_3,REF_4,REF_5,REF_6,REF_7,REF_8,REF_9,REF_10,REF_11,REF_Year,NEW_Type,NEW_ES_Con0,NEW_ES_Con1,NEW_ES_Con2,NEW_ES_Con3,NEW_ES_Con4,NEW_ES_Con5,NEW_HS_Con0,NEW_HS_Con1,NEW_HS_Con2,NEW_HS_Con3,NEW_HS_Con4,NEW_HS_Con5,NEW_HS_Con6,NEW_HS_Con7,NEW_HS_Con8,NEW_HS_Con9,NEW_HP_Con0,NEW_HP_Con1,NEW_HP_Con2,NEW_HP_Con3,NEW_HP_Con4,NEW_HP_Con5,NEW_Year,TRIG_1Text,TRIG_2Text,TRIG_1,TRIG_2,TRIG_3,TRIG_4,SUB,SUB_1,SUB_2,SUB_3,SUB_5,SUB_4,INFO_S1,INFO_S2,INFO_S3,INFO_S4,INFO_S5,INFO_S6,INFO_S7,INFO_S8,INFO_S9,INFO_S10,INFO_S11,INFO_S12,INFO_C1,INFO_C2,INFO_C3,INFO_C4,INFO_C5,INFO_C6,INFO_C7,INFO_C8,INFO_C9,INFO_PAS,INFO_ACT,CHAR_B1,CHAR_B2,CHAR_B3,CHAR_B4,CHAR_HS1,CHAR_HS2,CHAR_HS3,CHAR_HS4,CHAR_HS5,CHAR_HS6,CHAR_HS7,BUILD_Type,BUILD_Size,BUILD_Use,BUILD_Use_Year,BUILD_Residence,BUILD_Age,BUILD_ES_Cur,BUILD_ES_Old,BUILD_HS1,BUILD_HS2,BUILD_HS3,BUILD_HS4,BUILD_HS5,BUILD_HS6,BUILD_HS7,BUILD_HS8,BUILD_HS9,BUILD_HS10,BUILD_HP,BUILD_HS1_Old,BUILD_HS2_Old,BUILD_HS3_Old,BUILD_HS4_Old,BUILD_HS5_Old,BUILD_HS6_Old,BUILD_HS7_Old,BUILD_HS8_Old,BUILD_HS9_Old,BUILD_HS10_Old,BUILD_HS_Age,SOCIO_Gender1,SOCIO_Age1,SOCIO_Country1,HOUSE_Education,HOUSE_Size1,HOUSE_Size2,HOUSE_Size3,HOUSE_Size4,HOUSE_Size5,HOUSE_Size6,HOUSE_Size7,HOUSE_Size8,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer,Gemeindename
1646,1647,1,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,None,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Energie Kosten,Autark sein,1.0,1.0,2.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,2.0,2,2.0,2,1,2.0,4.0,4.0,4.0,1.0,1.0,2.0,2,3.0,1,30.0,1.0,5,4.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,2.0,1994.0,1.0,3.0,5.0,0,0,0,0,0,0,0,2.0,0,1,2.0,62379,Feldbach
1647,1648,1,1,0,0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,2022,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Heizkosten,Stromkosten,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,2.0,3.0,3,2.0,2,2,3.0,2.0,3.0,2.0,3.0,3.0,2.0,2,3.0,1,42.0,1.0,6,4.0,6.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,2.0,1969.0,1.0,4.0,0.0,0,0,0,0,2,0,0,3.0,1,0,3.0,61265,Schladming
1648,1649,1,1,1,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,vor 2010,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,vor 2010,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Wohnmöglichkeit für Tochter,Lärmschutz,2.0,2.0,2.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,3.0,1.0,2,2.0,2,2,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2,2.0,1,26.0,1.0,1,6.0,6.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,2.0,1948.0,2.0,4.0,0.0,0,0,2,0,1,1,0,6.0,1,0,NaN,61444,Scheifling
1649,1650,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,2.0,3.0,3.0,2.0,2.0,3.0,2.0,2,2.0,1,40.0,1.0,6,6.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,1.0,1947.0,1.0,4.0,0.0,0,0,0,0,0,0,2,4.0,0,0,6.0,61108,Leoben
1650,1651,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,5,5,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2,2.0,1,30.0,1.0,7,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,2.0,1957.0,1.0,2.0,NaN,0,0,1,0,1,1,0,3.0,0,0,6.0,61750,Strallegg

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1651 entries, 0 to 1650
Columns: 143 entries, id to Gemeindename
dtypes: float64(115), int64(16), object(12)
memory usage: 1.8+ MB

In [68]:
df.describe()

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,REN_6,REN_7,REF_1,REF_2,REF_3,REF_4,REF_5,REF_6,REF_7,REF_8,REF_9,REF_10,REF_11,NEW_Type,NEW_ES_Con0,NEW_ES_Con1,NEW_ES_Con2,NEW_ES_Con3,NEW_ES_Con4,NEW_ES_Con5,NEW_HS_Con0,NEW_HS_Con1,NEW_HS_Con2,NEW_HS_Con3,NEW_HS_Con4,NEW_HS_Con5,NEW_HS_Con6,NEW_HS_Con7,NEW_HS_Con8,NEW_HS_Con9,NEW_HP_Con0,NEW_HP_Con1,NEW_HP_Con2,NEW_HP_Con3,NEW_HP_Con4,NEW_HP_Con5,TRIG_1,TRIG_2,TRIG_3,TRIG_4,SUB,SUB_1,SUB_2,SUB_3,SUB_5,SUB_4,INFO_S1,INFO_S2,INFO_S3,INFO_S4,INFO_S5,INFO_S6,INFO_S7,INFO_S8,INFO_S9,INFO_S10,INFO_S11,INFO_S12,INFO_C1,INFO_C2,INFO_C3,INFO_C4,INFO_C5,INFO_C6,INFO_C7,INFO_C8,INFO_C9,INFO_PAS,INFO_ACT,CHAR_B1,CHAR_B2,CHAR_B3,CHAR_B4,CHAR_HS1,CHAR_HS2,CHAR_HS3,CHAR_HS4,CHAR_HS5,CHAR_HS6,CHAR_HS7,BUILD_Type,BUILD_Size,BUILD_Use,BUILD_Use_Year,BUILD_Residence,BUILD_Age,BUILD_ES_Cur,BUILD_ES_Old,BUILD_HS1,BUILD_HS2,BUILD_HS3,BUILD_HS4,BUILD_HS5,BUILD_HS6,BUILD_HS7,BUILD_HS8,BUILD_HS9,BUILD_HS10,BUILD_HP,BUILD_HS1_Old,BUILD_HS2_Old,BUILD_HS3_Old,BUILD_HS4_Old,BUILD_HS5_Old,BUILD_HS6_Old,BUILD_HS7_Old,BUILD_HS8_Old,BUILD_HS9_Old,BUILD_HS10_Old,SOCIO_Gender1,SOCIO_Age1,SOCIO_Country1,HOUSE_Education,HOUSE_Size1,HOUSE_Size2,HOUSE_Size3,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer
count,1651.000000,1651.000000,1651.000000,1651.000000,1651.000000,836.000000,836.000000,836.000000,836.000000,836.000000,836.000000,382.000000,1198.000000,1198.000000,1198.000000,1198.000000,1198.000000,1198.000000,1198.000000,1198.000000,1183.000000,1155.000000,391.000000,287.000000,38.0,22.0,119.0,69.0,41.0,24.0,8.0,26.0,5.0,22.0,101.0,74.0,2.0,164.0,105.0,0.0,2.0,70.0,53.0,16.0,67.0,1.0,1446.000000,1449.000000,1278.000000,1444.000000,1476.000000,805.0,968.0,775.0,19.0,34.0,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,547.000000,461.0,1035.0,91.0,45.0,501.0,73.0,1143.0,143.0,52.0,1473.000000,1290.000000,1651.000000,1475.000000,1651.000000,1651.000000,1650.000000,1650.000000,1649.000000,1649.000000,1648.000000,1649.000000,1650.000000,1651.000000,1642.000000,1651.000000,1587.000000,1647.000000,1651.000000,1650.000000,1192.000000,114.0,184.0,119.0,957.0,486.0,47.0,359.0,513.0,53.0,1.0,359.000000,5.0,491.0,72.0,274.0,200.0,23.0,17.0,50.0,54.0,3.0,1649.000000,1628.000000,1644.000000,1645.000000,1641.000000,1651.000000,1651.000000,1563.000000,1651.000000,1651.000000,1459.000000,1651.000000
mean,826.000000,0.725621,0.506360,0.173834,0.105391,0.586124,0.723684,0.221292,0.255981,0.309809,0.537081,0.583770,0.361436,0.520033,0.235392,0.522538,0.748748,0.308013,0.481636,0.534224,0.268808,0.188745,0.145780,1.411150,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.860304,1.911663,2.075117,3.030471,0.821816,1.0,1.0,1.0,1.0,1.0,0.622884,0.445498,0.988490,1.012864,0.205823,0.358835,0.756940,0.834123,0.838186,0.366960,0.982397,0.160878,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.015614,2.827132,2.961841,2.060339,2.763174,1.697759,2.123030,2.900606,3.086113,2.000606,1.631675,2.251061,2.341212,1.188976,1.372107,0.964870,25.880907,1.025501,5.404603,4.354545,5.041946,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.245125,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.796847,1967.627150,1.074209,3.094225,0.203534,0.308904,0.114476,3.349328,0.502726,0.543307,2.714873,61355.621442
std,476.746963,0.446336,0.500111,0.379082,0.307149,0.492822,0.447443,0.415365,0.436672,0.462691,0.498922,0.493579,0.480617,0.499807,0.424421,0.499700,0.433914,0.461865,0.499871,0.499036,0.443527,0.391475,0.353338,0.678038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,1.089040,1.044815,1.117522,1.021141,0.406838,0.0,0.0,0.0,0.0,0.0,0.828419,0.743017,0.761899,0.665016,0.575840,0.653227,0.718391,0.838747,0.807454,0.749484,0.742415,0.527352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.892542,1.323667,0.693955,0.749323,0.784084,0.721187,0.823409,0.777839,0.958411,1.044809,0.789052,1.204276,0.930873,0.391608,0.642608,0.184165,17.109736,0.157689,2.423587,1.446350,0.902419,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.297213,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.405472,12.423501,0.472588,0.850216,0.554373,0.666269,0.402540,1.199996,0.500144,0.498272,1.824875,776.359956
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1925.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,60101.000000
25%,413.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,2.000000,1.000000,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,3.000000,2.000000,2.000000,1.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,11.000000,1.000000,4.000000,3.000000,5.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1958.000000,1.000000,2.000000,0.000000,0.000000,0.000000,2.500000,0.000000,0.000000,1.000000,60654.000000
50%,826.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,2.000000,2.000000,3.000000,1.000000,1.0,1.0,1.0,1.0,1.0,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,3.000000,3.000000,2.000000,3.000000,2.000000,2.000000,3.000000,3.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,25.000000,1.000000,5.000000,4.000000,5.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1967.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,1.000000,1.000000,2.000000,61413.000000
75%,1238.500000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,2.000000,3.000000,4.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.000000,3.000000,3.000000,2.000000,3.000000,2.000000,2.000000,3.000000,4.000000,2.000000,2.000000,3.000000,3.000000,1.000000,2.000000,1.000000,38.000000,1.000000,7.000000,6.000000,6.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000,1977.000000,1.000000,4.000000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000,4.000000,62139.000000
max,1651.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,5.000000,5.000000,5.000000,5.000000,2.000000,1.0,1.0,1.0,1.0,1.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,2.000000,5.000000,1.000000,81.000000,2.000000,11.000000,6.000000,6.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.000000,1999.000000,7.000000,5.000000,5.000000,6.000000,4.000000,7.000000,1.000000,1.000000,6.000000,62390.000000

### Show all columns

In [69]:
pd.set_option('display.max_columns', None)
df

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,REN_6,REN_7,REN_Year,REF_1,REF_2,REF_3,REF_4,REF_5,REF_6,REF_7,REF_8,REF_9,REF_10,REF_11,REF_Year,NEW_Type,NEW_ES_Con0,NEW_ES_Con1,NEW_ES_Con2,NEW_ES_Con3,NEW_ES_Con4,NEW_ES_Con5,NEW_HS_Con0,NEW_HS_Con1,NEW_HS_Con2,NEW_HS_Con3,NEW_HS_Con4,NEW_HS_Con5,NEW_HS_Con6,NEW_HS_Con7,NEW_HS_Con8,NEW_HS_Con9,NEW_HP_Con0,NEW_HP_Con1,NEW_HP_Con2,NEW_HP_Con3,NEW_HP_Con4,NEW_HP_Con5,NEW_Year,TRIG_1Text,TRIG_2Text,TRIG_1,TRIG_2,TRIG_3,TRIG_4,SUB,SUB_1,SUB_2,SUB_3,SUB_5,SUB_4,INFO_S1,INFO_S2,INFO_S3,INFO_S4,INFO_S5,INFO_S6,INFO_S7,INFO_S8,INFO_S9,INFO_S10,INFO_S11,INFO_S12,INFO_C1,INFO_C2,INFO_C3,INFO_C4,INFO_C5,INFO_C6,INFO_C7,INFO_C8,INFO_C9,INFO_PAS,INFO_ACT,CHAR_B1,CHAR_B2,CHAR_B3,CHAR_B4,CHAR_HS1,CHAR_HS2,CHAR_HS3,CHAR_HS4,CHAR_HS5,CHAR_HS6,CHAR_HS7,BUILD_Type,BUILD_Size,BUILD_Use,BUILD_Use_Year,BUILD_Residence,BUILD_Age,BUILD_ES_Cur,BUILD_ES_Old,BUILD_HS1,BUILD_HS2,BUILD_HS3,BUILD_HS4,BUILD_HS5,BUILD_HS6,BUILD_HS7,BUILD_HS8,BUILD_HS9,BUILD_HS10,BUILD_HP,BUILD_HS1_Old,BUILD_HS2_Old,BUILD_HS3_Old,BUILD_HS4_Old,BUILD_HS5_Old,BUILD_HS6_Old,BUILD_HS7_Old,BUILD_HS8_Old,BUILD_HS9_Old,BUILD_HS10_Old,BUILD_HS_Age,SOCIO_Gender1,SOCIO_Age1,SOCIO_Country1,HOUSE_Education,HOUSE_Size1,HOUSE_Size2,HOUSE_Size3,HOUSE_Size4,HOUSE_Size5,HOUSE_Size6,HOUSE_Size7,HOUSE_Size8,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer,Gemeindename
0,1,1,1,0,0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,2022,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,NaN,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Hoher Energieverbrauch, Kälte von unten",Auszug der Mutter ins Altersheim,3.0,1.0,1.0,4.0,1.0,NaN,1.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,3.0,3.0,3,2.0,3,1,2.0,4.0,3.0,1.0,3.0,5.0,2.0,1,2.0,1,46.0,1.0,5,6.0,6.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2014,1.0,1966.0,5.0,4.0,0.0,0,0,0,0,1,1,0,4.0,1,1,1.0,61263,Rottenmann
1,2,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2018,Familiengründung - Geburt von Kindern,Umzug von Wien in die Oststeiermark,2.0,2.0,NaN,2.0,1.0,NaN,1.0,NaN,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,3.0,NaN,3,2.0,3,1,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1,1.0,1,5.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,2.0,1984.0,1.0,4.0,2.0,0,0,0,2,0,0,0,5.0,0,0,5.0,62233,Pinggau
2,3,0,1,0,0,1.0,1.0,0.0,0.0,0.0,1.0,NaN,vor 2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,2.0,3.0,2.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,3.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,3.0,3.0,3,1.0,3,1,1.0,4.0,4.0,1.0,1.0,1.0,2.0,1,2.0,1,9.0,1.0,5,4.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,2.0,1977.0,1.0,3.0,0.0,1,0,0,0,1,0,0,3.0,0,0,NaN,61255,Bad Mitterndorf
3,4,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Haus war renovierungsbedürftig,Alte Fassade aus Eternit,1.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,3.0,3,2.0,2,2,3.0,2.0,3.0,1.0,1.0,3.0,5.0,1,1.0,0,NaN,1.0,4,3.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,2.0,1959.0,1.0,3.0,0.0,0,0,0,0,0,2,0,3.0,1,1,1.0,60350,Stainz
4,5,1,1,0,0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,vor 2010,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,NaN,vor 2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Hauskauf,None,1.0,1.0,1.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,3.0,4,1.0,4,1,1.0,4.0,4.0,1.0,1.0,1.0,1.0,1,1.0,1,4.0,1.0,6,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,2.0,1971.0,1.0,4.0,0.0,0,2,0,0,2,0,0,4.0,1,1,1.0,61757,Birkfeld
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1646,1647,1,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,None,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Energie Kosten,Autark sein,1.0,1.0,2.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,2.0,2,2.0,2,1,2.0,4.0,4.0,4.0,1.0,1.0,2.0,2,3.0,1,30.0,1.0,5,4.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,2.0,1994.0,1.0,3.0,5.0,0,0,0,0,0,0,0,2.0,0,1,2.0,62379,Feldbach
1647,1648,1,1,0,0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,2022,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Heizkosten,Stromkosten,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,2.0,3.0,3,2.0,2,2,3.0,2.0,3.0,2.0,3.0,3.0,2.0,2,3.0,1,42.0,1.0,6,4.0,6.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,2.0,1969.0,1.0,4.0,0.0,0,0,0,0,2,0,0,3.0,1,0,3.0,61265,Schladming
1648,1649,1,1,1,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,vor 2010,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,vor 2010,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Wohnmöglichkeit für Tochter,Lärmschutz,2.0,2.0,2.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,3.0,1.0,2,2.0,2,2,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2,2.0,1,26.0,1.0,1,6.0,6.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,2.0,1948.0,2.0,4.0,0.0,0,0,2,0,1,1,0,6.0,1,0,NaN,61444,Scheifling
1649,1650,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,2.0,3.0,3.0,2.0,2.0,3.0,2.0,2,2.0,1,40.0,1.0,6,6.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,1.0,1947.0,1.0,4.0,0.0,0,0,0,0,0,0,2,4.0,0,0,6.0,61108,Leoben
1650,1651,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,5,5,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2,2.0,1,30.0,1.0,7,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,2.0,1957.0,1.0,2.0,NaN,0,0,1,0,1,1,0,3.0,0,0,6.0,61750,Strallegg

### GROUP_BEH - clustering of households by the depth of change to green energy

In [70]:
df["GROUP_BEH"].value_counts()

GROUP_BEH
1.0    581
2.0    247
5.0    183
6.0    174
3.0    169
4.0    105
Name: count, dtype: int64

### Classification Reference

| Code | Label | Meaning |
|------|-------|---------|
| 1 | HIGH | Transition Leader — Changed main heating system and did thermal renovation |
| 2 | MED_CO2 | CO2 Reducers — Changed main heating to renewable |
| 3 | MED_SAV | Energy Savers — Thermally insulated only |
| 4 | LOW | Technology Adopters — Only minor innovations (PV, battery, etc.) |
| 5 | NEW | New Builders — Built/rebuilt rather than retrofitted |
| 6 | NO | No Actions — Did nothing. |
| — | — | Cannot be assigned (the 192 missing) |

In [71]:
df["SUB"].value_counts()

SUB
1.0    1185
0.0     277
2.0      14
Name: count, dtype: int64

In [73]:
df[df["REF_Thermische_Sanierung"] == 1].count()

id                          830
MEAS_REF                    830
MEAS_REN                    830
MEAS_NEW                    830
MEAS_NO                     830
                           ...
REF_Thermische_Sanierung    830
REF_Heizungstausch          830
GROUP_BEH                   750
Gemeindenummer              830
Gemeindename                830
Length: 143, dtype: int64